### ISSUE TITLE
Update Redshift driver

### ISSUE THREAD

**Issue by alondhe** [OHDSI/DatabaseConnectorJars#5]
On RHEL, the current Redshift driver does not work. It gets stuck on the connect step. I've tested with the latest driver (https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.20.1043/RedshiftJDBC4-no-awssdk-1.2.20.1043.jar), and it works now.

**Comment by JamesSWiggins** [comment]
So, I've noticed that when I pull the master branch, it causes errors with Achilles running against OMOP in Redshift (snippet below).  It ultimately causes Achilles to fail.  I was able to resolve these issues by using DatabaseConnectorJars v1.0.0.  Not sure if this is related to changes in the DatabaseConnectorJars code or the use of a newer Redshift driver...

```
50%Error: Error executing SQL:
java.sql.SQLException: [Amazon](500310) Invalid operation: relation "#s_tmpach_116" does not exist;
An error report has been created at /tmp/errorReport.txt
```

**Comment by alondhe** [comment]
Odd, we've been using the new driver for all our CDM builds without issue. Any chance you can check in with the Redshift team about this?

**Comment by schuemie** [comment]
I think this issue has now been resolved in the develop branch of DatabaseConnector. Could you give that a try?

**Comment by JamesSWiggins** [comment]
@alondhe @schuemie 

Sorry for the delay in testing this.  Yes, I tried cloning the 'develop' branch of DatabaseConnector and it works with DatabaseConnectorJars 'master' branch.  To be specific, the below package versions seem to be compatible.

> packageVersion("DatabaseConnectorJars")
[1] ‘1.1.0’
> packageVersion("DatabaseConnector")
[1] ‘2.4.1’
